#theme: minima
plugins:
  - jekyll-include-cache
remote_theme: rundocs/jekyll-rtd-theme
title: Social Neurocognition
description: Course book for PSYC 53.14 (Spring 2021)
author: Arjen Stolk
baseurl: "/"
twitter_username: StolkArjen
github_username:  StolkArjen
home_page_in_navbar: false 
google_analytics_id: UA-44870891-1
