theme: minima #jekyll-theme-slate
title: Social Neurocognition
description: Course book for PSYC 53.14 (Spring 2021)
baseurl: "/"
twitter_username: StolkArjen
github_username:  StolkArjen

{% for item in site.data.navigation.toc %}
    <h3>{{ item.title }}</h3>
      <ul>
        {% for entry in item.subfolderitems %}
          <li><a href="{{ entry.url }}">{{ entry.page }}</a></li>
        {% endfor %}
      </ul>
  {% endfor %}
