theme: minima
#remote_theme: "mmistakes/jekyll-theme-basically-basic"
#remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: Social Neurocognition
description: Course book for PSYC 53.14 (Spring 2021)
author: Arjen Stolk
baseurl: "/"
twitter_username: StolkArjen
github_username:  StolkArjen
home_page_in_navbar: false 
google_analytics_id: UA-44870891-1
